products = [
    ('Mango', 'Mango'),
    ('Apple', 'Apfel'),
    ('Tomato', 'Tomaten'),
    ('Lemon', 'Zitrone'),
    ('Spinach', 'Spinat'),
    ('Grape', 'Traube'),
    ('Plum', 'Zwetschge'),
    ('Orange', 'Orange'),
    ('Avocado', 'Avocado'),
    ('Pineapple', 'Ananas'),
    ('Lime', 'Limette'),
    ('Ginger', 'Ingwer'),
    ('Carrot', 'Karotte'),
    ('Kiwi', 'Kiwi'),
    ('Onion', 'Zwiebel'),
    ('Sweet Potato', 'Süsskartoffel'),
    ('Nectarine', 'Nektarine'),
    ('Pomegranate', 'Granatapfel'),
    ('Broccoli', 'Broccoli'),
    ('Zucchini', 'Zucchetti'),
    ('Banana', 'Banane'),
    ('Potato', 'Kartoffel'),
]